### PR TITLE
Fast-forward Foxy to 1.0.1

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. Assuming reviewers agree these changes are pure bug fixes.

### CODE REVIEW

**Comment by hidmic** [comment]
Foxy CI up to `test_communication`, including `rosidl_typesupport_c` and `rosidl_typesupport_cpp`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11914/)
* ~Linux-aarch64~ (No RTI Connext on ARM64)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9708/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11931/)

**Review by jacobperron — APPROVED** [review]
LGTM

**Review by dirk-thomas — APPROVED** [review]
Assuming CI will pass green.

**Comment by hidmic** [comment]
@ros-pull-request-builder retest this please

**Comment by hidmic** [comment]
Windows CI's finally green. @jacobperron good to go?

**Comment by ivanpauno** [comment]
@hidmic be careful with the `delete-merged-branch` bot :joy: (see https://github.com/ros2/ros2/issues/1015).
We should enable branch protection.

**Comment by hidmic** [comment]
Yeap, realized too late. Thanks for restoring the branch. I made `master` the default branch again too.

**Pull request merged**
