### PR TITLE
Pass macro dep to cppcheck 

### PR DESCRIPTION
**Pull request by claireyywang**
part of the effort to pin cppcheck 2.0, https://github.com/ros2/ros2/issues/942
Signed-off-by: claireyywang <22240514+claireyywang@users.noreply.github.com>

### CODE REVIEW

**Comment by claireyywang** [comment]
CI
linux [Build Status](https://ci.ros2.org/job/ci_linux/11326/)
linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/6565/)
osx [Build Status](https://ci.ros2.org/job/ci_osx/9290/)
windows [Build Status](https://ci.ros2.org/job/ci_windows/11222/)

**Review by ivanpauno — APPROVED** [review]
Same comment than https://github.com/ros2/rosidl_typesupport/pull/78.

**Review by sloretz — APPROVED** [review]

**Comment by hidmic** [comment]
@claireyywang ping

**Comment by clalancette** [comment]
Closing this, since we aren't going to backport this to Foxy and we no longer use this package in Galactic and Rolling.

**Pull request closed without merging**
