### PR TITLE
Ignore -Wclass-memaccess build warnings coming from Connext 5.3.1

### PR DESCRIPTION
**Pull request by jacobperron**
These warnings appear on Ubuntu Focal, e.g. http://build.ros2.org/view/Fci/job/Fci__nightly-connext_ubuntu_focal_amd64/50/warnings24Result/

### CODE REVIEW

**Review by hidmic — APPROVED** [review]
LGTM pending quiet CI, though I think that based on [the description of the warning](https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html#index-Wclass-memaccess), this warrants a separate issue for tracking and resolution.

**Comment by jacobperron** [comment]
> I think that based on the description of the warning, this warrants a separate issue for tracking and resolution.

If I'm not mistaken, I think the warnings are coming from Connext 5.3.1 headers. I'm not sure where to ticket it. But I would hope that the warnings have been addressed in later version of Connext already, which we may switch to eventually pending https://github.com/ros2/rmw_connext/issues/375

**Comment by hidmic** [comment]
Oh I see. Nevermind then.

**Comment by jacobperron** [comment]
CI: https://github.com/ros2/rmw_connext/pull/396#issuecomment-599735290

**Pull request merged**
