### PR TITLE
Remove redundant logic

### PR DESCRIPTION
**Pull request by jacobperron**
Depends on https://github.com/ros2/rosidl/pull/432

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Review by dirk-thomas — APPROVED** [review]

**Comment by dirk-thomas** [comment]
Technically this one will need a minimum version dependency on the next version of `rosidl_generator_c`.

**Comment by jacobperron** [comment]
> Technically this one will need a minimum version dependency on the next version of rosidl_generator_c.

Right. I can make a note for myself to add the version to the dependency when we release `rosidl_generator_c`.

**Comment by jacobperron** [comment]
For posterity, CI is here: https://github.com/ros2/rosidl/pull/432#issuecomment-576978604

**Comment by jacobperron** [comment]
Now that `rosidl_generator_c` is released, I've opened a follow-up adding the minimum version dependency: https://github.com/ros2/rosidl_typesupport_connext/pull/54

**Pull request merged**
